### PR TITLE
fixed compilation issues in LispWorks 6.1

### PR DESCRIPTION
**Pull request by binghe**
In LispWorks, complex LOOP generates code containing MACROLET, which is a special operator not supported by Screamer's WALK function. To work around of this issue, some complex LOOPs used in screamer code were rewritten into simple LOOPs or DO loops.

### CODE REVIEW

**Comment by fighting-spirit** [comment]
From reading the code, this is the same as pull request #13 (Feb-2013). or is it another thing?

**Comment by binghe** [comment]
Screamer 3.24 from Ubuntu source package: https://launchpad.net/ubuntu/+source/cl-screamer/3.24.2-3

**Comment by binghe** [comment]
Yes, you’re right, but now I have pushed more: the whole Screamer 3.24 from the following Ubuntu source package:

https://launchpad.net/ubuntu/+source/cl-screamer/3.24.2-3
https://launchpad.net/ubuntu/+source/cl-plus/1.0-3

with some other changes to ASD files.

I believe the 3.24 version is from the original author, and this time it can be compiled in LispWorks.

--
Chun

Il giorno 28/apr/2015, alle ore 20:47, fighting-spirit <notifications@github.com> ha scritto:

**Comment by nikodemus** [comment]
Sorry about being slow about things, and many thanks for the pull request.

I'm going to be asinine about screamer+, and won't merge commits that touch it until I have permission from the author to change the license to match Screamer proper (or at least something FOSS-sane, preferably MIT/BSD). I've tried, but didn't get very far - and have run out of steam on that front for now. If someone wants to have a go, I'm all thumbs up.

At this point re. screamer+ my recommendation would be to keep it in separate repository. The licence is a mess.

I'm going to incorporate the Lispworks fix, but with reader-conditionals removed and "KLUDGE: don't rewrite using a complex loop - Lispworks will expand into a macrolet, which iterate won't like" or something to the effect.

The other stuff I didn't yet look at. I'll merge the straightforward things today.

Also, please make a pull-request per logical item, each on their own branch. This ties in too many things.

**Comment by nikodemus** [comment]
Re. the debian changes. They look mostly bogus. Like someone has checked out the old version of debian screamer on top of this one.

FAQ is definitely bogus. (old)
Makefile overrides mine and breaks my infra. Definitely not.
README is definitely bogus. (old)
equations.lisp gets a ton of whitespace changes with bad indentation and re-introduces reader-conditionals

etc. No, no, no.

**Comment by binghe** [comment]
Hi,

I think you just merge whatever you think useful and I’ll delete my repository after that. For Screamer+, It took me some time trying to find the source code on Internet and finally I got them, I think I’ll create another separated repository for them and make sure it depends on your package, until the license issue gets more clear. I thought the Debian package represent the latest work from original author, maybe I was wrong about this ...

Regards,

Chun

Il giorno 18/giu/2015, alle ore 12:21, Nikodemus Siivola <notifications@github.com> ha scritto:

**Comment by nikodemus** [comment]
Maybe -- but my stuff is on top of the latest from the original author. :)

Eg. moving the changelog from screamer.lisp to ChangeLog.old is in my tree -- merging the debian stuff just splatted it right back in there.

I'll push something soonish.

Again, thanks for looking after Screamer!

**Comment by nikodemus** [comment]
Pushed.

**Pull request closed without merging**
